import {getChatGPTUser} from '../../chatgpt-auth';
import {database} from '../../../db/shared';
import {z} from 'zod';
export const dynamic='force-dynamic';
const task=z.object({id:z.number().int().nonnegative(),title:z.string().trim().min(1).max(180),owner:z.string().max(80),core:z.boolean(),status:z.enum(['Pending','Building','Blocked','Done','Cut']),due:z.string().max(40).optional(),doneWhen:z.string().max(500).optional()});
const requirement=z.object({title:z.string().trim().min(1).max(180),owner:z.string().max(80),url:z.string().max(1000),done:z.boolean()});
const doc=z.object({brief:z.object({user:z.string().max(500),problem:z.string().max(1500),flow:z.string().max(1000),measure:z.string().max(1000)}),timing:z.object({start:z.number().finite(),idea:z.number().finite(),final:z.number().finite()}).refine(t=>t.start<t.idea&&t.idea<=t.final,'Invalid event timings'),tasks:z.array(task).max(100).refine(t=>new Set(t.map(x=>x.id)).size===t.length,'Duplicate task IDs'),requirements:z.array(requirement).min(1).max(40),rules:z.string().max(5000)});
function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
function code(){return crypto.randomUUID().replaceAll('-','')}
async function view(id:string,userId:string){const db=database();const membership=await db.prepare('SELECT user_id FROM members WHERE project_id=? AND user_id=?').bind(id,userId).first();if(!membership)return null;const project=await db.prepare('SELECT id,name,owner,document,revision,updated_at FROM projects WHERE id=?').bind(id).first<any>();if(!project)return null;const people=await db.prepare('SELECT display_name FROM members WHERE project_id=?').bind(id).all();return {id:project.id,name:project.name,owner:project.owner,revision:project.revision,updatedAt:project.updated_at,document:JSON.parse(project.document),members:people.results}}
function sameOrigin(request:Request){if(request.headers.get('sec-fetch-site')==='cross-site')return false;const origin=request.headers.get('origin');return !origin||origin===new URL(request.url).origin}
export async function GET(request:Request){try{const user=await getChatGPTUser();if(!user)return json({error:'Sign in with ChatGPT to use saved projects.'},401);const id=new URL(request.url).searchParams.get('id');if(id){const project=await view(id,user.userId);return project?json({project,user:{name:user.displayName}}):json({error:'Project unavailable or you are not a member.'},404)}const rows=await database().prepare('SELECT p.id,p.name,p.updated_at FROM projects p JOIN members m ON m.project_id=p.id WHERE m.user_id=? ORDER BY p.updated_at DESC').bind(user.userId).all();return json({projects:rows.results,user:{name:user.displayName}})}catch{return json({error:'Project storage is unavailable. Please retry.'},503)}}
export async function POST(request:Request){try{if(!sameOrigin(request))return json({error:'Invalid request origin.'},403);const user=await getChatGPTUser();if(!user)return json({error:'Sign in with ChatGPT first.'},401);if(Number(request.headers.get('content-length')||0)>100000)return json({error:'Project is too large.'},413);const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>100000)return json({error:'Project is too large.'},413);const body:any=JSON.parse(raw);if(!body||typeof body!=='object'||Array.isArray(body))return json({error:'Invalid request.'},400);const db=database();if(body.action==='create'){const name=z.string().trim().min(1).max(100).parse(body.name),document=doc.parse(body.document);const id=crypto.randomUUID(),invite=code();await db.batch([db.prepare('INSERT INTO projects (id,owner,name,invite_hash,document,revision,updated_at) VALUES (?,?,?,?,?,1,?)').bind(id,user.userId,name,await hash(invite),JSON.stringify(document),Date.now()),db.prepare('INSERT INTO members (project_id,user_id,display_name) VALUES (?,?,?)').bind(id,user.userId,user.displayName)]);return json({project:await view(id,user.userId),inviteCode:invite},201)}if(body.action==='join'){const invite=z.string().regex(/^[a-f0-9]{32}$/i).parse(body.code.trim().toLowerCase());const p=await db.prepare('SELECT id FROM projects WHERE invite_hash=?').bind(await hash(invite)).first<any>();if(!p)return json({error:'Join code not found. Ask your project owner for a current code.'},404);await db.prepare('INSERT OR IGNORE INTO members (project_id,user_id,display_name) VALUES (?,?,?)').bind(p.id,user.userId,user.displayName).run();return json({project:await view(p.id,user.userId)})}const id=z.string().uuid().parse(body.id);const existing=await view(id,user.userId);if(!existing)return json({error:'Project unavailable or you are not a member.'},404);if(body.action==='invite'){if(existing.owner!==user.userId)return json({error:'Only the project owner can create a join code.'},403);const invite=code();await db.prepare('UPDATE projects SET invite_hash=? WHERE id=?').bind(await hash(invite),id).run();return json({inviteCode:invite})}if(body.action==='save'){const document=doc.parse(body.document),revision=z.number().int().positive().parse(body.revision);const result=await db.prepare('UPDATE projects SET document=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(document),Date.now(),id,revision).run();if(!result.meta.changes)return json({error:'A teammate changed this project. Reload the latest version before saving.',conflict:true},409);return json({project:await view(id,user.userId)})}return json({error:'Unknown action.'},400)}catch(error){if(error instanceof z.ZodError)return json({error:'Check required fields, timing order and field lengths.'},400);if(error instanceof SyntaxError)return json({error:'Invalid request.'},400);return json({error:'Unable to save right now. Your input remains on screen; retry.'},503)}}
